### ISSUE TITLE
not really an issue but failed to get `Practical Principled FRP: Forget the past, change the future`

### ISSUE THREAD

**Issue by brucou** [ocharles/papers#8]
Hello charles,

for some reason I wanted to get `Practical Principled FRP: Forget the past, change the future` but failed to do so due to a problem with git annex. Would you by any chance be able to post shortly (or have a ftp link) for the article. Could not get it online either as the swedish university repository on which it was hosted has changed its link.

Thanks!

**Comment by ocharles** [comment]
That's odd, the whole point of this repository is that everything is meant to be available from the Internet Archive:

```
git annex whereis Practical\ Principled\ FRP:\ Forget\ the\ past,\ change\ the\ future,\ FRPNow\!.pdf      ~/papers
whereis Practical Principled FRP: Forget the past, change the future, FRPNow!.pdf (5 copies) 
        00000000-0000-0000-0000-000000000001 -- web
        0219a4a2-d457-4327-9589-e3bbcc6f9530 -- desktop [here]
        7478d291-87ef-4d50-9f94-c20a45fdfbf6 -- ollie@nixos:~/papers
        7af6d260-e83c-4f10-99dc-cb5e5035ded3 -- [ia]
        dd8c879d-44f5-4c20-8e2d-4706e8a2163d -- ollie@io:~/papers

  web: http://archive.org/download/ocharles-papers/SHA256E-s406737--39d7257f7d4294399db806c61fde4d5aad90109f8b1438d59b95932a209e749a.pdf
  web: http://www.cse.chalmers.se/~atze/papers/prprfrp.pdf
ok
```

What happens when you do

```
git annex get Practical\ Principled\ FRP:\ Forget\ the\ past,\ change\ the\ future,\ FRPNow\!.pdf
```?

**Comment by brucou** [comment]
Thanks Charles.

The link `http://www.cse.chalmers.se/~atze/papers/prprfrp.pdf` is the one who is no longer active. The archive one is working fine (`http://archive.org/download/ocharles-papers/SHA256E-s406737--39d7257f7d4294399db806c61fde4d5aad90109f8b1438d59b95932a209e749a.pdf`).

When I do `git annex ...`, I get `git: 'annex' is not a git command. See 'git --help'`, while I do have git annex installed. I believe the problem is that I am on windows (10), and there must be some incompatibility there. It happens sometimes. 

In any case thank you very much for the direct download link !

**Comment by ocharles** [comment]
Ok, I'm not bothered if the chalmers link no longer works, all that is important to me is that `git annex get` gets you the paper.

> When I do git annex ..., I get git: 'annex' is not a git command. See 'git --help', while I do have git annex installed. I believe the problem is that I am on windows (10), and there must be some incompatibility there. It happens sometimes.

That just sounds to me like you don't have Git annex installed correctly.

If you got the paper though and are happy, is it OK to close this issue?

**Comment by brucou** [comment]
Yes, sure. Thanks again!
